workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60

    integrations:
      app_store_connect: CodeMagic API

    
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ras3ucat.bingeQuest

    working_directory: execution/frontend/flutter

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
