workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    integrations:
      app_store_connect: Codemagic API   

    working_directory: execution/frontend/flutter

    scripts:
      - name: Debug path
        script: |
          echo "PWD:"
          pwd
          echo "FILES:"
          ls -la

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
