workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    # Ensure this matches your repo exactly: 'execute' vs 'execution'
    working_directory: execution/frontend/flutter

    integrations:
      app_store_connect: Codemagic API

    environment:
      flutter: stable
      xcode: latest
      groups:
        - secure
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ras3ucat.bingeQuest

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-number=$PROJECT_BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
