workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    working_directory: execution/frontend/flutter

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
