// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8MLmydnYZ5VeZiyHjF_3B3lKPsaY7iIk',
    appId: '1:58540891155:web:edf32b75c27514bf1fb3e6',
    messagingSenderId: '58540891155',
    projectId: 'binge-quest',
    authDomain: 'binge-quest.firebaseapp.com',
    storageBucket: 'binge-quest.firebasestorage.app',
    measurementId: 'G-KVDN6GCR13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW52g1MtlvhlUkYvzzPnw1Y3Wakw-AmfQ',
    appId: '1:58540891155:android:7543c59ae7426f491fb3e6',
    messagingSenderId: '58540891155',
    projectId: 'binge-quest',
    storageBucket: 'binge-quest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi3J5ZTeoapW6EexPOHBCK03bHoiIpFQk',
    appId: '1:58540891155:ios:c8330fdae03fe7b41fb3e6',
    messagingSenderId: '58540891155',
    projectId: 'binge-quest',
    storageBucket: 'binge-quest.firebasestorage.app',
    iosBundleId: 'com.ras3ucat.bingeQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi3J5ZTeoapW6EexPOHBCK03bHoiIpFQk',
    appId: '1:58540891155:ios:c8330fdae03fe7b41fb3e6',
    messagingSenderId: '58540891155',
    projectId: 'binge-quest',
    storageBucket: 'binge-quest.firebasestorage.app',
    iosBundleId: 'com.ras3ucat.bingeQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8MLmydnYZ5VeZiyHjF_3B3lKPsaY7iIk',
    appId: '1:58540891155:web:7e6ec7d263a4411d1fb3e6',
    messagingSenderId: '58540891155',
    projectId: 'binge-quest',
    authDomain: 'binge-quest.firebaseapp.com',
    storageBucket: 'binge-quest.firebasestorage.app',
    measurementId: 'G-053GDNN76T',
  );
}
